### PR TITLE
Create collection optionally accepts an ownerId

### PR DESCRIPTION
**Pull request by konnorjp**

### CODE REVIEW

**Comment by reynoldsnlp** [comment]
@konnorjp Are the failing tests not a problem here? Do we need to fix the tests to make this pass?

**Comment by konnorjp** [comment]
I'm close to having everything work. I didn't know that we had tests when I first made the pull request. I thought that we would have to deploy the server again before we knew if my changes worked. I've gotten a bit of help from Santi to get through some of the bugs already. But I'll need to take some more time next week to finish it.

**Comment by reynoldsnlp** [comment]
sounds good.

**Comment by konnorjp** [comment]
I talked to Santi. The test that it fails on is not implemented yet. So all is good. We can merge and deploy into the develop branch.

**Comment by reynoldsnlp** [comment]
@konnorjp Do we need to just delete that test that is not implemented yet? (or comment it out)

**Pull request merged**
